// Centralized DOM references for the app.
window.AppDom = {
    versionSelect: document.getElementById('version-select'),
    dropArea: document.getElementById('drop-area'),
    fileInput: document.getElementById('file-input'),
    loadedState: document.getElementById('loaded-state'),
    successMessage: document.getElementById('success-message'),
    fileNameDisplay: document.getElementById('file-name-display'),
    preview: document.getElementById('skin-preview'),
    removeButton: document.getElementById('remove-btn'),
    downloadButton: document.getElementById('download-btn'),
    usernameLabel: document.getElementById('username-label'),
    usernameInput: document.getElementById('username-input'),
    loadSkinButton: document.getElementById('load-skin-btn'),
    usernameFeedback: document.getElementById('username-feedback'),
    toggleDetailsBtn: document.getElementById('toggle-details-btn'),
    detailsContainer: document.getElementById('details-container'),
    howToListContainer: document.getElementById('how-to-list-container'),
    privacyModal: document.getElementById('privacy-modal'),
    privacyLink: document.getElementById('privacy-link'),
    modalCloseBtn: document.getElementById('modal-close-btn'),
    secretFeatureOverlay: document.getElementById('secret-feature-overlay'),
    secretFeatureCloseButton: document.getElementById('secret-feature-close'),
    howToTitle: document.getElementById('how-to-title'),
    zipStructureTitle: document.getElementById('zip-structure-title'),
    privacyTitle: document.getElementById('privacy-title'),
    privacyTextContainer: document.getElementById('privacy-text'),
    clickSound: document.getElementById('mc-click-sound'),
    achievementSound: document.getElementById('mc-achievement-sound'),
    downloadSound: document.getElementById('mc-download-sound'),
    errorToast: document.getElementById('error-toast'),
    errorToastText: document.getElementById('error-toast-text')
};

